### ISSUE TITLE
"manager-role" cluster role is too permissive with ops.dac.nokia.com ApiGroup resources

### ISSUE THREAD

**Issue by ptrszlgy** [nokia/industrial-application-framework#26]
"manager-role" cluster role should be fine tuned in order to prevent the App Operator to overwrite the existing state information in the resource request CRs, only the resource Spec change should be allowed.

https://github.com/nokia/industrial-application-framework/blob/e08cdd1acc9d2145f503815a4f6f67c6e8918b52/consul-operator/config/rbac/role.yaml#L65

Symptom: In case of operator restart it re-processes the existing App CRs and as part of the process it re-generates then re-applies all manifests. In case of resource request CRs, this process overwrites the existing state and finalizer section which leads further misbehavior later in Application lifecycle management.   

How to reproduce:
- Operator Update
- Pod/Container restart

**Comment by hochdorf** [comment]
This issue is addressed from the AppFW side. Apps cannot modify the protected sections (status, annotation) of the platform resource requests.
